# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  solution: '**\OAuthClient.sln'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test Home.OAuthClients.Tests --configuration $(buildConfiguration) --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- powershell: .\codecov.ps1 -token $(CODECOV_TOKEN)
  displayName: Upload to CodeCov.io